### ISSUE TITLE
As a user I want to be able to create notes

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#10]
### Description
As a user I want to be able to create notes
so I know what to remember

### Tasks
- [x] **1t:** Create alert method
- [x] **2t:** Implement non-deleteable storage
- [x] **1t:** Create addNote method
- [x] **1t:** Write about it
- [x] **2t:** Compare to native way
- [x] **1t:** Style the page

### Acceptance criterias
- [x] I can create notes
- [x] It looks nice

### Definition of Done
- [x] Tested
- [x] Reviewed
