### ISSUE TITLE
As a user I want to be able to delete notes by swiping

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#11]
### Description
As a user I want to be able to delete notes by swiping
so it will be easy to me to delete notes

Dependent on #10 

### Tasks
- [x] **2t:** Create swipe functionality
- [x] **2t:** Implement delete method
- [x] **2t:** Write about it
- [x] **2t:** Compare to native way

### Acceptance criterias
- [x] I can delete a note by swiping

### Definition of Done
- [x] Tested
- [x] Reviewed
