### ISSUE TITLE
As a user I want to get informed when a note is deleted 

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#12]
### Description
As a user I want to get informed when a note is deleted 
so that I know that it has been done

Dependent on #11 

### Tasks
- [x] **2t:** Create a toast provider
- [x] **2t:** Implement toast method
- [x] **1t:** Write about it
- [x] **1t:** Compare to native way

### Acceptance criterias
- [x] I get informed when a note is deleted

### Definition of Done
- [x] Tested
- [x] Reviewed
