### ISSUE TITLE
As a user I want to have a map that shows where I am

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#13]
### Description
As a user I want to have a map that shows where I am
so that I can see where I am

### Tasks
- [x] **2t:** Research possibilities 
- [x] **3t:** Implement maps
- [x] **1t:** Write about it
- [x] **2t:** Compare with native way
- [x] **1t:** Style page 

### Acceptance criterias
- [x] I can see where I am

### Definition of Done
- [x] Tested
- [x] Reviewed
