### ISSUE TITLE
As a user I want to be able to turn the GPS on and off

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#14]
### Description
As a user I want to be able to turn the GPS on and off
so that it would not drain my battery

### Tasks
- [x] **2t:** Create method that turn it on or off
- [x] **1t:** Create on/off button
- [x] **1t:** Write about it
- [x] **1t:** Compare to native way 

### Acceptance criterias
- [x] I can turn the GPS on and off

### Definition of Done
- [x] Tested
- [x] Reviewed
