### ISSUE TITLE
As a user I want to check the weather for a chosen city

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#15]
### Description
As a user I want to check the weather for a chosen city
so that I know what weather it is going to be

### Tasks
- [x] **2t:** Find restAPI that works
- [x] **1t:** Generate new page 
- [x] **4t:** Implement API on new page
- [x] **2t:** Write about it
- [x] **2t:** Compare to native way
- [x] **2t:** Style the page(s)

### Acceptance criterias
- [x] I can check the weather
- [x] It looks nice

### Definition of Done
- [x] Tested
- [x] Reviewed
