### ISSUE TITLE
As a user I want to see a list of users shared uploads

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#16]
### Description
As a user I want to see a list of users shared uploads
so I can get an overview of it

### Tasks
- [x] **3t:** Research possibilities
- [x] **3t:** Set up backend
- [x] **2t:** Implement backend
- [x] **3t:** Write about it
- [x] **2t:** Compare to native way

### Acceptance criterias
- [x] I can see users shared uploads
- [x] The backend works

### Definition of Done
- [x] Tested
- [x] Reviewed
