### ISSUE TITLE
As a user I want to see a selected user upload

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#17]
### Description
As a user I want to see a selected user upload
so that I can see what the user have uploaded

Dependent on #16 

### Tasks
- [ ] **2t:** Pass data to new page
- [ ] **2t:** Set up new page template
- [ ] **2t:** Write about it
- [ ] **1t:** Compare to native way
- [ ] **2t:** Style the page
- [ ] **1t:** Write about it

### Acceptance criterias
- [ ] I can see the selected user upload
- [ ] It looks nice 

### Definition of Done
- [ ] Tested
- [ ] Reviewed
