### ISSUE TITLE
As a user I want to upload a experience

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#18]
### Description
As a user I want to upload a experience
so others can see my upload

### Tasks
- [x] **1t:** Generate new page component
- [x] **2t:** Set up and style html template
- [x] **1t:** Research native-camera implentation
- [x] **2t:** Create camera method in ts/html
- [x] **4t:** Store image in Google Firebase
- [x] **1t:** Push upload to Firebase
- [x] **1t:** Get upload from Firebase
- [x] **2t:** Write about it
- [x] **2t:** Compare to native way 

### Acceptance criterias
- [x] I can upload an experience
- [x] It looks nice

### Definition of Done
- [x] Tested
- [x] Reviewed
