### ISSUE TITLE
As a user I want a different color on the statusbar

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#19]
### Description
As a user I want a different color on the statusbar
so that it will look good

### Tasks
- [x] **1t:** Implement new color
- [x] **1t:** Write about it
- [x] **1t:** Compare to native way

### Acceptance criterias
- [x] It looks nice

### Definition of Done
- [x] Tested
- [x] Reviewed
