### ISSUE TITLE
As a developer I want to set the project up in Atom

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#2]
### Description
As a developer I want to set the project up in Atom, so that I am ready for Sprint 1.

### Tasks
- [x] **2t:** Set up project
- [x] **1t:** Upload to Github
- [x] **4t:** Write about it

### Acceptance criterias
- [x] I can run the project without errors
