### ISSUE TITLE
As a user I want an icon for the app

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#20]
### Description
As a user I want an icon for the app
so that I know the app quickly

### Tasks
- [x] **1t:** Create an icon
- [x] **1t:** Implement icon
- [x] **1t:** Write about it
- [x] **1t:** Compare to native way

### Acceptance criterias
- [x] The icon is updated

### Definition of Done
- [x] Tested
- [x] Reviewed
