### ISSUE TITLE
As a user I want a different splash screen picture

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#21]
### Description
As a user I want a different splash screen picture
so that it will feel more personal

### Tasks
- [x] **1t:** Find another program than MS Paint
- [x] **1t:** Create new splash screen.
- [x] **1t:** Implement new splash screeng
- [x] **1t:** Write about it
- [x] **2t:** Compare to native way

### Acceptance criterias
- [x] The splash screen is updated

### Definition of Done
- [x] Tested
- [x] Reviewed
