### ISSUE TITLE
As a developer I want to know the difference between Hybrid and Native

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#3]
### Description
As a developer I want to know the difference between Hybrid and Native
so that I can talk about it, and I get clewer.

### Tasks
- [x] **3t:** Read about the difference
- [x] **3t:** Write about it

### Acceptance criterias
- [x] I can talk about the difference, and I know what both are
