### ISSUE TITLE
As a user I want to se a loading bar/spinner when i wait for data

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#34]
### Description
As a user I want to se a loading bar/spinner when i wait for data
so I know that something is happening

### Tasks
- [x] **3t:** Research possibilities
- [x] **2t:** Create a loading provider
- [x] **3t:** Implement loading where needed
- [x] **2t:** Write about it
- [x] **2t:** Compare to native way

### Acceptance criterias
- [x] I see loading progress when I wait for data

### Definition of Done
- [x] Tested
- [x] Reviewed
