### ISSUE TITLE
As a user I want to access the flashlight in the app

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#39]
### Description
As a user I want to access the flashlight in the app
so I don't have to close the app to use the flashlight

### Tasks
- [ ] **1t:** Find a good spot in the app form the function
- [ ] **3t:** Implement method
- [ ] **1t:** Styling
- [ ] **1t:** Write about it
- [ ] **1t:** Compare to native way

Samlet: **7t**

### Acceptance criterias
- [ ] I can use the flashlight

### Definition of Done
- [ ] Tested
- [ ] Reviewed
