### ISSUE TITLE
As a developer I want to know that the pros and cons are with hyrid and native

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#4]
### Description
As a developer I want to know that the pros and cons are with hyrid and native
So that I get more knowlegde.

### Tasks
- [x] **2t:** Read about the pros and cons
- [x] **2t:** Write about it

### Acceptance criterias
- [x] I know what the pros and cons are
