### ISSUE TITLE
As a user I want a different header color in multitask window

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#40]
### Description
As a user I want a different header color in multitask window
so that it will be more unik to me

### Tasks
- [ ] **1t:** Research
- [ ] **1t:** Implement new color
- [ ] **1t:** Write about it
- [ ] **2t:** Compare to native way

Samlet: **5t**

### Acceptance criterias
- [ ] I can see a new color

### Definition of Done
- [ ] Tested
- [ ] Reviewed
