### ISSUE TITLE
As a user I want to clear what I have written in add post fields by shaking the phone

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#41]
### Description
As a user I want to clear what I have written in add post fields by shaking the phone
So that it will be easy to me to clear the fields

### Tasks
- [x] **1t:** Research
- [x] **3t:** Implement shake gesture in post-add.ts
- [x] **2t:** Write about it
- [ ] **2t:** Compare to native way

Samlet **8t**

### Acceptance criterias
- [x] I can shake to clear fields

### Definition of Done
- [x] Tested
- [x] Reviewed
