### ISSUE TITLE
As a user I want tabs

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#5]
### Description
As a user I want tabs 
so I can navigate between pages

### Tasks
- [x] **2t:** Set up tabs structure
- [x] **1t:** Write about it
- [x] **1t:** Compare to Native way

### Acceptance criterias
- [x] I can navigate between pages

### Definition of Done
- [x] Tested
- [x] Reviewed
