### ISSUE TITLE
As a user I want a list of different guides

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#6]
### Description
As a user I want a list of different guides
so that I can see what guides there is

### Tasks
- [x] **1t:** Create list template
- [x] **3t:** Find and create code structure
- [x] **1t:** Style list
- [x] **2t:** Write about it
- [x] **1t:** Compare to Native way

### Acceptance criterias
- [x] I can see different guides
- [x] They look nice

### Definition of Done
- [x] Tested
- [x] Reviewed
