### ISSUE TITLE
As a user I want to be able to click on a guide and see its content in a new list

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#7]
### Description
As a user I want to be able to click on a guide and see its content in a new list
so that it will be easy to navigate
Dependent on #6 

### Tasks
- [x] **1t:** Create new page
- [x] **1t:** Create list
- [x] **1t:** Fill with data
- [x] **1t:** Style the list
- [x] **2t:** Write about it
- [x] **2t:** Compare with Native way

### Acceptance criterias
- [x] I can see a new list of the selected guide's content
- [x] It looks nice

### Definition of Done
- [x] Tested
- [x] Reviewed
