### ISSUE TITLE
As a user I want to see the content that I have clicked on in a list

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#8]
### Description
As a user I want to see the content that I have clicked on in a list
so I can read about the things I want

Dependent on #6 
Dependent on #7 

### Tasks
- [x] **1t:** Create modal
- [x] **1t:** Fill with data
- [x] **2t:** Style the template so it looks nice
- [x] **1t:** Write about it
- [x] **1t:** Compare to Native way

### Acceptance criterias
- [x] I can see the content that I have clicked on
- [x] It looks nice

### Definition of Done
- [x] Tested
- [x] Reviewed
