### ISSUE TITLE
As a user I want to be able to search on a item in a selected list

### ISSUE THREAD

**Issue by kimmeyera** [KIMB0/NatureSurvival#9]
### Description
As a user I want to be able to search on a item in a selected list
so that I can easy find the item I am looking for

Dependent on #6 
Dependent on #7 

### Tasks
- [x] **1t:** Create search field in list
- [x] **3t:** Make the search work
- [x] **1t:** Right about i
- [x] **2t:** Compare to Native way

### Acceptance criterias
- [x] I can search through the list

### Definition of Done
- [x] Tested
- [x] Reviewed
